name: Deploy to EC2

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Connect to EC2 instance and copy code
      uses: appleboy/ssh-action@v0.3.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          rsync -avzr --delete ./* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/ubuntu/Teamit-django-backend-1/